language: java
sudo: true
install: true
addons:
  sonarcloud:
    organization: "wesleyosantos91-github"
    token:
      secure: $SONAR_TOKEN

jdk:
  - oraclejdk11

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script:
  - mvn clean compile
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=wesleyosantos91_poc-api-first-quarkus
before_install:
  - chmod +x mvnw